# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/05_cli.ipynb (unless otherwise specified).

__all__ = ['firehr_from_banet_events']

# Cell
from pathlib import Path
import re
import numpy as np
from fastscript import *
from fire_split.core import save_data
from .data import get_event_data
from .predict import get_preds

# Cell
@call_parse
def firehr_from_banet_events(
        file:Param("BA-Net event tif file",str),
        path:Param("Path to save outputs",str)='.',
        composite_days_before:Param("Time window for composite before fire",int)=120,
        composite_days_after:Param("Time window for composite after fire",int)=60):
    path = Path(path)
    event_id = '_'.join(Path(file).stem.split('_')[1:])
    year = int(re.findall('(\d{4})', Path('PT2020_233/ba100m_PT2020_233.tif').stem.split('_')[1])[0])
    im, transform, crs = get_event_data(
        event_id, year, file, composite_days=[composite_days_before,composite_days_after])
    preds = get_preds(im)
    save_data(path/f'firehr_{event_id}.tif', (preds*255).astype(np.uint8), crs=crs, transform=transform)